// ── Account & User ──
export const ACCOUNT_STATUS = {
  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED",
  ARCHIVED: "ARCHIVED",
};

export const STUDENT_STATUS = {
  PASSED: "PASSED",
  FAILED: "FAILED",
  IN_TRAINING: "IN_TRAINING",
  CERTIFICATE_SEEKER: "CERTIFICATE_SEEKER",
};

export const GENDER = {
  MALE: "MALE",
  FEMALE: "FEMALE",
};

export const INSTRUCTOR_TYPE = {
  MANUAL: "MANUAL",
  AUTOMATIC: "AUTOMATIC",
  BOTH: "BOTH",
};

// ── Booking & Vehicles ──
export const VEHICLE_TYPE = {
  MANUAL: "MANUAL",
  AUTOMATIC: "AUTOMATIC",
};

export const VEHICLE_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
};

export const VEHICLE_SOURCE = {
  SCHOOL_CAR: "SCHOOL_CAR",
  STUDENT_CAR: "STUDENT_CAR",
};

export const BOOKING_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  BOOKED: "BOOKED",
  COMPLETED: "COMPLETED",
  NO_SHOW: "NO_SHOW",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
};

export const PAYMENT_STATUS = {
  PENDING_DEPOSIT: "PENDING_DEPOSIT",
  DEPOSIT_PAID: "DEPOSIT_PAID",
  FULLY_PAID: "FULLY_PAID",
  DEPOSIT_NON_REFUNDABLE: "DEPOSIT_NON_REFUNDABLE",
  DEPOSIT_AVAILABLE_FOR_REBOOKING: "DEPOSIT_AVAILABLE_FOR_REBOOKING",
  DEPOSIT_USED_IN_REBOOKING: "DEPOSIT_USED_IN_REBOOKING",
};

export const TRAINING_TYPE = {
  MANUAL: "MANUAL",
  AUTOMATIC: "AUTOMATIC",
};

export const VEHICLE_UNAVAILABLE_REASON = {
  MAINTENANCE: "MAINTENANCE",
  UNAVAILABLE: "UNAVAILABLE",
  OUT_OF_SERVICE: "OUT_OF_SERVICE",
};

// ── Charges & Payments ──
export const CHARGE_REASON = {
  LESSON_DEPOSIT: "LESSON_DEPOSIT",
  LESSON_REMAINDER: "LESSON_REMAINDER",
  CERTIFICATE_FEE: "CERTIFICATE_FEE",
  TRANSPORT_LECTURE: "TRANSPORT_LECTURE",
  TRANSPORT_EXAM: "TRANSPORT_EXAM",
  REEXAM_THEORY: "REEXAM_THEORY",
  REEXAM_PRACTICAL: "REEXAM_PRACTICAL",
  OTHER: "OTHER",
};

export const CHARGE_STATUS = {
  PAID: "PAID",
  UNPAID: "UNPAID",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  CANCELLED: "CANCELLED",
};

export const PAYMENT_METHOD = {
  CASH: "CASH",
  SHAM_CASH: "SHAM_CASH",
};

// ── Expenses ──
export const EXPENSE_CATEGORY = {
  VEHICLE: "VEHICLE",
  INSTRUCTOR: "INSTRUCTOR",
  EMPLOYEE: "EMPLOYEE",
  GENERAL: "GENERAL",
};

export const EXPENSE_STATUS = {
  PAID: "PAID",
  UNPAID: "UNPAID",
};

export const VEHICLE_EXPENSE_REASON = {
  MAINTENANCE: "MAINTENANCE",
  GAS: "GAS",
  INSURANCE: "INSURANCE",
  OTHER: "OTHER",
};

export const EMPLOYEE_EXPENSE_TYPE = {
  SALARY: "SALARY",
  BONUS: "BONUS",
  OTHER: "OTHER",
};

export const GENERAL_EXPENSE_TYPE = {
  WATER: "WATER",
  ELECTRICITY: "ELECTRICITY",
  INTERNET: "INTERNET",
  KITCHEN: "KITCHEN",
  SUPPLIES: "SUPPLIES",
  OTHER: "OTHER",
};

// ── Certificates ──
export const CERTIFICATE_CATEGORY = {
  B: "B",
  B1: "B1",
  C: "C",
  D: "D",
};

export const CERTIFICATE_REQUEST_STATUS = {
  WAITING_FOR_SERVICE_FEE: "WAITING_FOR_SERVICE_FEE",
  WAITING_FOR_TRAINING_SCHEDULE: "WAITING_FOR_TRAINING_SCHEDULE",
  IN_GOVERNMENT_TRAINING: "IN_GOVERNMENT_TRAINING",
  WAITING_FOR_PRACTICAL_EXAM: "WAITING_FOR_PRACTICAL_EXAM",
  WAITING_FOR_THEORETICAL_EXAM: "WAITING_FOR_THEORETICAL_EXAM",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const EXAM_TYPE = {
  THEORY: "THEORY",
  PRACTICAL: "PRACTICAL",
};

export const EXAM_RESULT = {
  PASS: "PASS",
  FAIL: "FAIL",
  ABSENT: "ABSENT",
};

// ── Transport ──
export const TRIP_TYPE = {
  LECTURE: "LECTURE",
  EXAM: "EXAM",
};

export const TRIP_STATUS = {
  SCHEDULED: "SCHEDULED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const REGISTRATION_STATUS = {
  REGISTERED: "REGISTERED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const ATTENDANCE_STATUS = {
  PENDING: "PENDING",
  ATTENDED: "ATTENDED",
  ABSENT: "ABSENT",
};

// ── Notifications ──
export const NOTIFICATION_TYPE = {
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_EXPIRED: "BOOKING_EXPIRED",
  PAYMENT_ACCEPTED: "PAYMENT_ACCEPTED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED",
  CERTIFICATE_STATUS_CHANGED: "CERTIFICATE_STATUS_CHANGED",
  INSTRUCTOR_SCHEDULE: "INSTRUCTOR_SCHEDULE",
  GENERAL: "GENERAL",
};

export const NOTIFICATION_CHANNEL = {
  IN_APP: "IN_APP",
  SMS: "SMS",
  PUSH: "PUSH",
};

export const NOTIFICATION_STATUS = {
  PENDING: "PENDING",
  SENT: "SENT",
  FAILED: "FAILED",
  READ: "READ",
};

// ── Auth ──
export const OTP_PURPOSE = {
  STUDENT_LOGIN: "STUDENT_LOGIN",
  PHONE_VERIFICATION: "PHONE_VERIFICATION",
  PASSWORD_RESET: "PASSWORD_RESET",
};

// ── Settings ──
export const SETTING_VALUE_TYPE = {
  NUMBER: "NUMBER",
  STRING: "STRING",
  TIME: "TIME",
  PERCENT: "PERCENT",
  BOOLEAN: "BOOLEAN",
};

// ── Days of Week ──
export const DAY_OF_WEEK = {
  SAT: "SAT",
  SUN: "SUN",
  MON: "MON",
  TUE: "TUE",
  WED: "WED",
  THU: "THU",
  FRI: "FRI",
};

// ── Cancellation Party ──
export const CANCELLATION_PARTY = {
  STUDENT: "STUDENT",
  VEHICLE: "VEHICLE",
  INSTRUCTOR: "INSTRUCTOR",
  SCHOOL: "SCHOOL",
};
